# Generated by Django 4.0.6 on 2022-07-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=100)),
                ('clubDescription', models.TextField(max_length=10000.0)),
                ('adminRollNo', models.CharField(max_length=9)),
                ('clubImage', models.ImageField(default='images/default.png', upload_to='images/')),
                ('clubLogo', models.ImageField(default='logos/default.png', upload_to='logos/')),
                ('clubLinks', models.CharField(max_length=100)),
                ('club_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=100)),
                ('memberRollNo', models.CharField(max_length=9)),
                ('memberImage', models.ImageField(default='images/default.png', upload_to='images/')),
                ('memberLinks', models.CharField(max_length=100)),
                ('memberClub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.club')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.TextField(max_length=10000.0)),
                ('projectImage', models.ImageField(default='images/default.png', upload_to='images/')),
                ('projectLinks', models.CharField(max_length=100)),
                ('project_updated_at', models.DateTimeField(auto_now=True)),
                ('projectClub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.club')),
                ('projectMembers', models.ManyToManyField(to='api.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='memberProjects',
            field=models.ManyToManyField(to='api.project'),
        ),
        migrations.AddField(
            model_name='club',
            name='clubMembers',
            field=models.ManyToManyField(to='api.member'),
        ),
        migrations.AddField(
            model_name='club',
            name='clubProjects',
            field=models.ManyToManyField(to='api.project'),
        ),
    ]
