# Generated by Django 4.0.6 on 2022-07-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000.0)),
                ('adminRollNo', models.CharField(max_length=9)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('logo', models.ImageField(default='logos/default.png', upload_to='logos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollNo', models.CharField(max_length=9)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000.0)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.clubs')),
            ],
        ),
    ]
